### ISSUE TITLE
Wouldn't it be smarter to use the queue implementation?

### ISSUE THREAD

**Issue by mateusfccp** [cassianomaia/Projeto-ED-1#2]
C++ has a [default queue implementation](http://www.cplusplus.com/reference/queue/queue/). Why not to use this?

**Comment by cassianomaia** [comment]
it's for a college class, data structs. We have to show that we know how to implement them without using standard libraries.

**Comment by mateusfccp** [comment]
Then, why don't you use pointer-based linked list instead of array? I think it's a more proper implementation.
